# .github/workflows/python-app.yml
name: Python Package

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12', '3.13']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      run: |
        pip install hatch  # Install hatch

    - name: Install just
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash
        echo "${HOME}/bin" >> $GITHUB_PATH

    - name: Install dependencies using just
      run: |
        just install  # This will run `hatch env create` to set up environment

    - name: Run tests using just
      run: |
        just test  # This will run `hatch run pytest` to run tests
