# .github/workflows/python-app.yml
name: Python Package

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12', '3.13']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      run: |
        pip install hatch  # Install hatch for dependency management
      shell: bash

    - name: Install Just on Linux and macOS
      if: runner.os != 'Windows'
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          curl --proto '=https' --tlsv1.2 -sSfL https://github.com/casey/just/releases/download/1.14.0/just-1.14.0-x86_64-unknown-linux-musl.tar.gz | tar -xz -C /usr/local/bin;
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          curl --proto '=https' --tlsv1.2 -sSfL https://github.com/casey/just/releases/download/1.14.0/just-1.14.0-x86_64-apple-darwin.tar.gz | tar -xz -C /usr/local/bin;
        fi
      shell: bash

    - name: Install Just on Windows
      if: runner.os == 'Windows'
      run: |
        # Create directory for just
        New-Item -Path C:\just -ItemType Directory -Force
        # Download and extract just to C:\just
        Invoke-WebRequest -Uri "https://github.com/casey/just/releases/download/1.14.0/just-1.14.0-x86_64-pc-windows-msvc.zip" -OutFile just.zip
        Expand-Archive -Path just.zip -DestinationPath C:\just
        # Add C:\just to the PATH environment variable
        $env:Path = "C:\just;" + $env:Path
        [System.Environment]::SetEnvironmentVariable('PATH', $env:Path, [System.EnvironmentVariableTarget]::Process)
        Write-Host "Updated PATH: $env:Path"
      shell: powershell

    - name: Verify Just Installation on Windows
      if: runner.os == 'Windows'
      run: |
        C:\just\just.exe --version
      shell: powershell

    - name: Install dependencies using Just
      run: just install  # This will run `hatch env create` via the justfile
      shell: bash

    - name: Run tests using Just
      run: just test  # This will run the 'test' task from justfile
      shell: bash
