# .github/workflows/python-app.yml
name: Python Package

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12', '3.13']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Just
      run: |
        case ${{ matrix.os }} in
          ubuntu-latest)
            curl --proto '=https' --tlsv1.2 -sSfL https://github.com/casey/just/releases/download/1.14.0/just-1.14.0-x86_64-unknown-linux-musl.tar.gz | tar -xz -C /usr/local/bin
            ;;
          macos-latest)
            curl --proto '=https' --tlsv1.2 -sSfL https://github.com/casey/just/releases/download/1.14.0/just-1.14.0-x86_64-apple-darwin.tar.gz | tar -xz -C /usr/local/bin
            ;;
          windows-latest)
            curl --proto '=https' --tlsv1.2 -sSfL https://github.com/casey/just/releases/download/1.14.0/just-1.14.0-x86_64-pc-windows-msvc.zip -o just.zip
            tar -xf just.zip -C /usr/local/bin
            ;;
        esac
        echo "/usr/local/bin" >> $GITHUB_PATH  # Add the path to the installed 'just'

    - name: Install dependencies using just
      run: |
        just install  # This will run the 'install' task from justfile

    - name: Run tests using just
      run: |
        just test  # This will run the 'test' task from justfile
